<?php


namespace zetsoft\service\tests;


use zetsoft\models\shop\ShopOrder;
use zetsoft\models\shop\ShopOrderItem;
use zetsoft\service\market\WareAccept;
use zetsoft\system\kernels\ZFrame;

class OtabekTest extends ZFrame
{
    #region Vars
    public $extension = '2000';

    #endregion

    #region Cores
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function test()
    {

    }
    #endregion


    #region Events
    public function eventStatus()
    {

    }

    #endregion

    #region Actions
    public function actionStatus()
    {

    }

    public function findItems(){

        $orders = ShopOrder::find()->all();
        vd($orders);


        $item = ShopOrderItem::find()->all();
        vd($item);

    }

    #endregion


}