<?php
/**
 * Class    LibreOffice
 * @package zetsoft\service\office
 *
 * @author Asror Zakirov
 * @license DilshodKhudoyarov
 *
 * https://www.ip2location.com/
 * Class file Ip2Loacation mamlakat, mintaqa, shahar, kenglik va uzunlik, pochta indeksi,
 * vaqt zonasi, ulanish tezligi, Internet provayderini aniqlash uchun IP-yechim
 */
namespace zetsoft\service\payer;

use zetsoft\system\Az;
use zetsoft\system\kernels\ZFrame;
use yii\httpclient\Client;

class PaymeTest extends ZFrame
{

    #region Vars

    public $database = Root . '\vendor/torann/geoip/resources/geoip.mmdb';

    #endregion

    # region Cores
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
    # endregion

    #region Test

    public function test()
    {
        $this->getInfoTest();
    }

    #endregion

    #region Function
    public function getinfo()
    {

        $client = new Client();
        $response = $client->createRequest()
            ->setMethod('POST')
            ->setUrl('/service/payer/paycom-integration-php-template/index.aspx')
            ->setHeaders(['Authorization' => 'Basic GZAHEwc&ZyR5wD&5Qf0T0wAeZ3IXe3V?rGJn'])
            ->setData([
                "id" => "1",
                "method" => "CheckPerformTransaction",
                "params" => [
                    "amount" => 5000,
                    "account" => [
                        "phone" => "974037243",
                    ],
                ],

            ])
            ->send();

        return $response;
    }
     #endregion

    #test_region

    #end_test_region
}
