<?php


namespace zetsoft\service\slug;

use voku\helper\URLify;
use zetsoft\system\kernels\ZFrame;

require Root . '/vendori/string/ALL/vendor/autoload.php';

/**
 * Class VokuUrlify
 * @package zetsoft\service\slug
 * @author NurbekMakhmudov
 * @Todo Convert any string into an valid and readable string for usage in the url.
 * https://github.com/voku/urlify
 * https://packagist.org/packages/voku/urlify
 */
class VokuUrlify extends ZFrame
{

    //start|NurbekMakhmudov|2020-10-15

    private $urlify;
    
    /**
     * initialization
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->urlify = new URLify();
    }

    /**
     * @param $msg
     * @return mixed
     * @author NurbekMakhmudov
     * $Todo Generate slugs for URLs
     */
    public function slug($msg)
    {
        if ($msg === null) return null;
        return $this->urlify->filter($msg);
    }


    #region Examples

    public function slugExample()
    {
//        echo $this->slug('Здравствуйте Артём , как дела.');
        echo $this->slug('مرحبا أرتيوم ، كيف حالك.');
    }

    #endregion


    //end|NurbekMakhmudov|2020-10-15

}